#+TITLE: Correction TD Électromagnétisme
#+AUTHOR: Xavier Garrido
#+DATE: 21/01/14
#+OPTIONS: ^:{} toc:2
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER_EXTRA: \newcommand{\vv}[1]{\overrightarrow{#1}}

* TD1 : Électromagnétisme & relativité

*Transformation de Lorentz :* $\beta=\tfrac{v}{c}$ et
 $\gamma=\tfrac{1}{\surd{1-\beta^2}}$. Si $\mathcal{R}^\prime$ est en mouvement
 rectiligne uniforme selon l'axe $x$ par rapport à $\mathcal{R}$ alors
 #+BEGIN_SRC latex
   \begin{equation*}
     \begin{bmatrix}
       ct^\prime\\x^\prime\\y^\prime\\z^\prime
     \end{bmatrix}
     =
     \begin{bmatrix}
       \gamma&-\beta\gamma&0&0\\
       -\beta\gamma&\gamma&0&0\\
       0&0&1&0\\
       0&0&0&1
     \end{bmatrix}
     \cdot
     \begin{bmatrix}
       ct\\x\\y\\z
     \end{bmatrix}
   \end{equation*}
 #+END_SRC
 et la transformation inverse
 #+BEGIN_SRC latex
   \begin{equation*}
     \begin{bmatrix}
       ct\\x\\y\\z
     \end{bmatrix}
     =
     \begin{bmatrix}
       \gamma&+\beta\gamma&0&0\\
       +\beta\gamma&\gamma&0&0\\
       0&0&1&0\\
       0&0&0&1
     \end{bmatrix}
     \cdot
     \begin{bmatrix}
       ct^\prime\\x^\prime\\y^\prime\\z^\prime
     \end{bmatrix}
   \end{equation*}
 #+END_SRC

*Transformation du champ EM :*

Composantes tangentielles au déplacement
$\vv{E}^\prime_\parallel=\vv{E}_\parallel$ et
$\vv{B}^\prime_\parallel=\vv{B}_\parallel$.

Composantes normales au déplacement
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}^\prime_\perp&= \gamma\,\left(\vv{E}_\perp+\vv{v}\times\vv{B}_\perp\right)\\
    \vv{B}^\prime_\perp&= \gamma\,\left(\vv{B}_\perp-\vv{v}\times\frac{\vv{E}_\perp}{c^2}\right)
  \end{align*}
#+END_SRC
ou
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)\\
    \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)
  \end{align*}
#+END_SRC

*Remarques :*
- les "quantités" perpendiculaires au déplacement telles les longueurs ($y$ et
  $z$ dans notre cas), ne subissent pas les effets de la relativité. Autrement
  dit une longueur $y$ restera inchangée sous la transformation
  $\mathcal{R}\rightarrow\mathcal{R}^\prime$ : $y=y\prime$

** Force entre des électrons qui se déplacent côte à côte

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.7\linewidth
[[file:./figures/referentiel_relat_1.pdf]]
#+END_CENTER

1) Soit $\mathcal{R}^\prime$ le référentiel où les particules sont au repos. Le
   champ électrique exercé sur $M_2$ par $M_1$ s'écrit
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}^\prime(M_2) = -\frac{e}{4\pi\epsilon_0\,d^2}\vv{u}_{z^\prime}
     \end{equation*}
   #+END_SRC
   /i.e./ le champ électrique coulombien. Les particules étant au repos, il n'y
   a pas de déplacement de charge donc $\vv{B}^\prime(M_2)=\vv{0}$. La force
   (coulombienne) qui s'exerce sur l'électron en $M_2$ est
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{F}^\prime(M_2)=-e\vv{E}^\prime(M_2)-e\vv{v}\times\vv{B}^\prime(M_2)=\frac{e^2}{4\pi\epsilon_0\,d^2}\vv{u}_{z^\prime}=-\vv{F}^\prime(M_1)
     \end{equation*}
   #+END_SRC
   soit une force répulsive.

2) Dans $\mathcal{R}$, on applique les règles de transformation du champ EM soit
   $\vv{E}^\prime_\parallel=\vv{E}_\parallel=\vv{0}$ et
   $\vv{B}^\prime_\parallel=\vv{B}_\parallel=\vv{0}$. Les composantes normales
   deviennent
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)\\
       \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)
     \end{align*}
   #+END_SRC
   On déduit que
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}_\perp=\gamma\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)=\gamma\vv{E}^\prime_\perp=-\frac{\gamma e}{4\pi\epsilon_0\,d^2}\vv{u}_z
     \end{equation*}
   #+END_SRC
   sachant que $\vv{u}_z=\vv{u}_{z^\prime}$.

   Le champ magnétique $\vv{B}_\perp$ est égal à
   $\gamma\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}$ soit
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{B}_\perp&=\frac{\gamma\,vE^\prime_\perp}{c^2}\,\vv{u}_x\times\vv{u}_z=-\frac{\gamma\,vE^\prime_\perp}{c^2}\,\vv{u}_y\\
       &=\frac{\gamma v}{c^2}\times\frac{e}{4\pi\epsilon_0\,d^2}\,\vv{u}_y\text{ avec } \mu_0\epsilon_0c^2=1\\
       &=\frac{\mu_0\gamma ve}{4\pi d^2}\vv{u}_y
     \end{align*}
   #+END_SRC
   La force résultante est égale à
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{F}(M_2)&=-e\vv{E}(M_2)-e\vv{v}\times\vv{B}(M_2)\\
       &=-e\gamma\vv{E}^\prime(M_2)+ev^2\vv{u}_x\times\vv{u_y}\frac{E^\prime(M_2)}{c^2}\\
       &=-e\gamma\vv{E}^\prime(M_2)\left[1-\frac{v^2}{c^2}\right]\text{ avec }\gamma=\frac{1}{\surd{1-v^2/c^2}}\\
       &=-e\gamma\vv{E}^\prime(M_2)\times\frac{1}{\gamma^2}=\frac{\vv{F}^\prime(M_2)}{\gamma}
     \end{align*}
   #+END_SRC
   Globalement, $F^\prime(M_2)>F(M_2)$. La force d'origine magnétique induite
   par le déplacement des particules compense l'augmentation de la force
   électrique de répulsion.

   *AN:*

   $\mathcal{E}=\gamma mc^2 - mc^2=(\gamma-1)mc^2$ donc
   $\gamma=1+\frac{\mathcal{E}}{mc^2}$. La masse de l'électron est 0.511 MeV.

   Pour $\mathcal{E}=\unit[1]{eV}$, $\gamma\sim1$
   #+BEGIN_SRC latex
     \begin{align*}
       F&=F^\prime=\frac{e^2}{4\pi\epsilon_0\,d^2}=\frac{e^2\mu_0c^2}{4\pi d^2}\\
       &=\frac{e^2c^2\times4\pi\,10^{-7}}{4\pi d^2}=\frac{(1.6\,10^{-19})^2\times(3\,10^8)^2\times10^{-7}}{(10^{-3})^2}\\
       &=\unit[2.3\,10^{-22}]{N}
     \end{align*}
   #+END_SRC

   Pour $\mathcal{E}=\unit[1]{MeV}$, $\gamma\simeq3$
   #+BEGIN_SRC latex
     \begin{align*}
       F&=\frac{F^\prime}{3}=\unit[7.7\,10^{-23}]{N}
     \end{align*}
   #+END_SRC

3) $v\rightarrow0$, $\beta\ll1$ et donc $\gamma\simeq1+\tfrac{\beta^2}{2}$
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{F}&=\frac{\vv{F}^\prime}{\gamma}\\
       &=\vv{F}^\prime\times\left(1-\beta^2\right)^{1/2}\\
       &\simeq\left(1-\tfrac{\beta^2}{2}\right)\vv{F}^\prime
     \end{align*}
   #+END_SRC
** Fil chargé
1) Dans $\mathcal{R}^\prime$, les charges électriques sont immobiles \equiv
   électrostatique. La charge électrique $Q^\prime$ se déduit de la densité
   linéique de charge $\lambda_0$
   #+BEGIN_SRC latex
     \begin{equation*}
       Q^\prime=\lambda_0\times\ell^\prime=\rho^\prime\times S^\prime\times\ell^\prime
     \end{equation*}
   #+END_SRC
   d'où $\rho^\prime=\tfrac{\lambda_0}{S^\prime}=\tfrac{\lambda_0}{S}$ car la
   surface $S$ est une quantité perpendiculaire au déplacement donc
   $S=S^\prime$.

   Les charges étant immobiles, il n'y a pas de courant d'où
   $\vv{j}^\prime=\vv{0}$ et donc pas de champ magnétique
   $\vv{B}^\prime=\vv{0}$. Le champ électrique $\vv{E}^\prime$ se déduit du
   théorème de Gauss, en évaluant au préalable, les symétries et les invariances
   de la distribution de charge. Ainsi, en coordonnées cylindriques où
   $\vv{u}_x=\vv{u}_z$, les plans $(\vv{u}_r,\vv{u}_\theta)$ et
   $(\vv{u}_r,\vv{u}_z)$ sont plans de symétrie de la distribution de charge. Le
   champ électrique résultant est donc contenu dans chacun de ces plans soit
   $\vv{E}(M) = E(M)\vv{u}_r$. Par ailleurs, la distribution de charge est
   invariante par rotation $\theta$ et par translation $x\equiv z$ donc
   $E(M)=E(r,\theta,z)=E(r)$.

   Le théorème de Gauss
   #+BEGIN_SRC latex
     \begin{equation*}
       \oiint_{\mathcal{S}}\vv{E}\cdot\text{d}\vv{S}=\frac{Q_\text{int.}}{\epsilon_0}
     \end{equation*}
   #+END_SRC
   où la surface de Gauss $\mathcal{S}$ est un cylindre de rayon $D^\prime$ et
   de hauteur $h$. En tenant compte des invariances et symétries de la
   distribution de charge, on obtient le champ $\vv{E}^\prime(M)$
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}^\prime(M)\times2\pi D^\prime\times h = \frac{\lambda_0\times h}{\epsilon_0}
     \end{equation*}
   #+END_SRC
   soit
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}^\prime(M)=\frac{\lambda_0}{2\pi\epsilon_0D^\prime}\vv{u}_r
     \end{equation*}
   #+END_SRC

2) Calculs dans $\mathcal{R}$
   1) Contraction des longeurs car $L$ est colinéaire au déplacement du
      cylindre.
      #+BEGIN_SRC latex
        \begin{equation*}
          L=\frac{L^\prime}{\gamma}\text{ mais } S = S^\prime\text{ car } S,S^\prime\perp\vv{u}
        \end{equation*}
      #+END_SRC

      Invariance de la charge électrique $Q=Q^\prime$ (ce postulat n'a jamais
      été mis en défaut).
      #+BEGIN_SRC latex
        \begin{equation*}
          Q=Q^\prime=\rho^\prime\times S^\prime\times L^\prime=\rho\times S\times L
        \end{equation*}
      #+END_SRC
      d'où
      #+BEGIN_SRC latex
        \begin{equation*}
          \rho=\rho^\prime\times\frac{L^\prime}{L}=\gamma\rho^\prime
        \end{equation*}
      #+END_SRC

      Densité de courant $\vv{j}$
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{j}=\rho\cdot\vv{u}=\rho u\vv{u}_x
        \end{equation*}
      #+END_SRC

      Le 4-vecteur $\vv{J}=(\rho c,\vv{j})$ est un 4-vecteur de Lorentz si
      l'égalité
      #+BEGIN_SRC latex
        \begin{equation*}
          \begin{bmatrix}
            \rho^\prime c\\j^\prime_x\\j^\prime_y\\j^\prime_z
          \end{bmatrix}
          =
          \begin{bmatrix}
            \gamma&-\beta\gamma&0&0\\
            -\beta\gamma&\gamma&0&0\\
            0&0&1&0\\
            0&0&0&1
          \end{bmatrix}
          \cdot
          \begin{bmatrix}
            \rho c\\j_x\\j_y\\j_z
          \end{bmatrix}
        \end{equation*}
       #+END_SRC
      La distribution de courant est nulle dans $\mathcal{R}^\prime$ donc
      $j^\prime_x=j^\prime_y=j^\prime_z=0$ $j_y=j_z=0$ et
      #+BEGIN_SRC latex
        \begin{align*}
          \gamma\rho c - \beta\gamma j_x&= \gamma\rho c-\beta\gamma\rho u\\
          &=\gamma\rho c-\beta\gamma\rho u\times\frac{c}{c}\\
          &=\gamma\rho c\left(1-\beta^2\right)\\
          &=\gamma\rho c\times\frac{1}{\gamma^2}=\frac{\rho c}{\gamma}\\
          &=\rho^\prime c
        \end{align*}
      #+END_SRC
      De même,
      #+BEGIN_SRC latex
        \begin{align*}
          -\beta\gamma\rho c+\gamma j_x&=-\beta\gamma\rho c+\gamma\rho u\\
          &=-\gamma\rho u+\gamma\rho u\\
          &=0=j^\prime_x
        \end{align*}
      #+END_SRC

   2) Calcul du champ électrique $\vv{E}(M)$

      Densité volumique et linéique de charge
      $\rho=\gamma\rho^\prime\rightarrow\lambda=\gamma\lambda_0$ d'où
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{E}(M)=\frac{\gamma\lambda_0}{2\pi\epsilon_0\,D}\vv{u}_r
        \end{equation*}
      #+END_SRC

      Le courant dans le fil est $\text{d}I=\vv{j}.\text{d}\vv{S}$ soit
      $I=j\times S$ et le champ magnétique $\vv{B}(M)$ s'écrit (/cf./ polycopié
      page 88, Chapitre Magnétostatique)
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}(M)&=\frac{\mu_0I}{2\pi\,D}\vv{u}_\theta\\
          &=\frac{\mu_0jS}{2\pi\,D}\vv{u}_\theta
        \end{align*}
      #+END_SRC
      or $j=\rho u=\gamma\rho^\prime u=\frac{\gamma\lambda_0u}{S}$ d'où
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}(M)&=\frac{\gamma\mu_0\lambda_0u}{2\pi\,D}\vv{u}_\theta\text{ avec } \mu_0\epsilon_0c^2=1\\
          \vv{B}(M)&=\frac{\gamma u}{c^2}E^\prime(M)\vv{u}_\theta
        \end{align*}
      #+END_SRC

3) Transformation des champs
   1) Transformation du champ électrique avec $\vv{B}^\prime=\vv{0}$
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{u}\times\vv{B}^\prime_\perp\right)\\
          \vv{E}(M)&= \gamma\,\vv{E}^\prime(M)\text{ vrai } \vv{E}(M)=\frac{\gamma\lambda_0}{2\pi\epsilon_0\,D}\vv{u}_r
        \end{align*}
      #+END_SRC

      Transformation du champ magnétique
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{u}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)\\
          \vv{B}(M)&=\gamma u\frac{E^\prime(M)}{c^2}\vv{u}_x\times\vv{u}_r\\
          &=\frac{\gamma u}{c^2}E^\prime(M)\vv{u}_\theta
        \end{align*}
      #+END_SRC

   2) $\vv{E}^\prime.\vv{B}^\prime=0$ et
      $\vv{E}.\vv{B}=\frac{\gamma^2u}{c^2}E^{\prime2}\,\vv{u}_\theta.\vv{u}_r=0$
   3)
      #+BEGIN_SRC latex
        \begin{align*}
          E^2-B^2c^2 &= (\gamma E^\prime)^2 - \left(\frac{\gamma u}{c^2}\right)^2E^{\prime2}c^2\\
          &=(\gamma E^\prime)^2\left(1-\frac{u^2}{c^2}\right)=E^{\prime2}\\
          &=E^{\prime2}-B^{\prime2}c^2\text{ puisque }B^\prime=0
        \end{align*}
      #+END_SRC

** Étude de la charge d'espace

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.7\linewidth
[[file:./figures/referentiel_relat_3.pdf]]
#+END_CENTER
À $t=t^\prime=0$, $R=R_0$ et $\dot{R}=\dot{R}^\prime=0$

1) dans $\mathcal{R}^\prime$, $\rho_0=$ constante
   1) Champ électrique $\vv{E}^\prime(M)$

      Les plans $(\vv{u}_r,\vv{u}_\theta)$ et $(\vv{u}_r,\vv{u}_{x^\prime})$
      sont des plans de symétrie de la distribution de charge \rightarrow le
      champ électrique appartient donc à chacun des plans :
      $\vv{E}^\prime(M)=E(M)\vv{u}_r$. De plus, il y a invariance par
      translation selon l'axe $x^\prime$ et par rotation d'angle \theta :
      $\vv{E}^\prime(M)=E(r)\vv{u}_r$.

      Théorème de Gauss :
      #+BEGIN_SRC latex
        \begin{equation*}
          \oiint_\mathcal{S}\vv{E}^\prime(M)\cdot\text{d}\vv{S}=\frac{Q_\text{int.}}{\epsilon_0}
        \end{equation*}
      #+END_SRC
      où la surface de Gauss est un cylindre de rayon $r<R$ et de hauteur $h$.
      #+BEGIN_SRC latex
        \begin{align*}
          E^\prime(r)\times2\pi r\times h&=\frac{\rho_0}{\epsilon_0}\times h\times\pi r^2\\
          \vv{E}^\prime(M)&=\frac{\rho_0r}{2\epsilon_0}\vv{u}_r=\frac{\rho_0}{2\epsilon_0}\vv{r}
        \end{align*}
      #+END_SRC

      Au voisinage de $r\sim R$, la force subie par une particule de charge $q$
      devient
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{F}^\prime=q\vv{E}^\prime(R)=\frac{q\rho_0}{2\epsilon_0}\vv{R}
        \end{equation*}
      #+END_SRC
      soit une force répulsive.
   2) Mécanique classique ou Newtonienne $\Upsigma\vv{F}=m\vv{a}$
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{F}^\prime&=m\vv{a}=m\ddot{R}\vv{u}_r=m\frac{\text{d}^2R}{\text{d}t^{\prime2}}\vv{u}_r\\
          \frac{q\rho_0}{2\epsilon_0}R\vv{u}_r&=m\ddot{R}\vv{u}_r\rightarrow\ddot{R}-\frac{q\rho_0}{2m\epsilon_0}R=0
        \end{align*}
      #+END_SRC
      Solutions du type $R(t^\prime)=Ae^{\alpha t^\prime}+Be^{-\alpha t^\prime}$
      où $\alpha^2=\tfrac{q\rho_0}{2m\epsilon_0}$. Or à $t^\prime=0$, $R=R_0$ et
      $\dot{R}=0$ d'où $A\alpha-B\alpha=0\rightarrow A=B$ et $A+B=R_0\rightarrow
      A=\tfrac{R_0}{2}$. La solution à l'équation différentielle est ainsi
      #+BEGIN_SRC latex
        \begin{equation*}
          R(t^\prime)=\frac{R_0}{2}e^{\alpha t^\prime}+\frac{R_0}{2}e^{-\alpha t^\prime}=R_0\cosh\alpha t^\prime
        \end{equation*}
      #+END_SRC
      On suppose que le mouvement transverse /i.e./ $R(t^\prime)$ est lent soit
      $\alpha t^\prime\ll1$. Le cosinus hyperbolique se réduit ainsi à
      $\cosh\alpha t^\prime\simeq1+\tfrac{(\alpha t^\prime)^2}{2}$. On déduit
      ainsi la variation relative de $R$
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}=\frac{R-R_0}{R_0}=\frac{R}{R_0}-1\simeq1+\frac{(\alpha t^\prime)^2}{2}-1&=\frac{\alpha^2}{2}t^{\prime2}\\
          &=\frac{q\rho_0}{4\epsilon_0m}t^{\prime2}
        \end{align*}
      #+END_SRC
   3) Dilatation du temps /i.e./ $t=\gamma t^\prime$ et $x=ut$ soit
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}=\frac{q\rho_0}{4\epsilon_0m}\frac{t^2}{\gamma^2}&=\frac{q\rho_0}{4\epsilon_0m}\times\frac{x^2}{\gamma^2u^2}\times\frac{c^2}{c^2}\\
          &=\frac{q\rho_0}{4\epsilon_0mc^2}\times\frac{x^2}{\gamma^2\beta^2}\text{ or }\gamma^2=\tfrac{1}{1-\beta^2},\gamma^2\beta^2=\gamma^2-1\\
          &=\frac{q\rho_0}{4\epsilon_0mc^2}\times\frac{x^2}{\gamma^2-1}
        \end{align*}
      #+END_SRC
2)
   1) Le champ électrique obéit aux mêmes règles d'invariance et de symétries
      que dans le référentiel $\mathcal{R}^\prime$ soit
      $\vv{E}(M)=E(r)\vv{u}_r$. Concernant le champ magnétique $\vv{B}(M)$, la
      densité de courant $\vv{j}=\rho\vv{u}$ est colinéaire à $\vv{u}_x$ et donc
      le plan $(\vv{u}_r,\vv{u}_x)$ est un plan de symétrie de la distribution
      de courant \rightarrow le champ magnétique est donc normal à ce plan soit
      $\vv{B}(M)=B(M)\vv{u}_\theta$. Par ailleurs, les mêmes règles d'invariance
      s'appliquent au champ magnétique : $\vv{B}(M)=B(r)\vv{u}_\theta$.
   2) Le calcul des champs électrique et magnétique se fait /via/ respectivement
      le théorème de Gauss et le théorème d'Ampère. Le champ électrique est
      ainsi
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{E}(M)=\frac{\rho}{2\epsilon_0}\vv{r}
        \end{equation*}
      #+END_SRC

      Le théorème d'Ampère :
      #+BEGIN_SRC latex
        \begin{equation*}
          \oint_{\mathcal{C}}\vv{B}.\text{d}\vv{\ell}=\oiint_\mathcal{S}\mu_0\vv{j}.\text{d}\vv{S}\text{ avec} \vv{j}=\rho u\vv{u}_x
        \end{equation*}
      #+END_SRC
      Le contour $\mathcal{C}$ est donc une boucle de rayon $r$ orientée suivant
      $\vv{u}_\theta$, la surface $\mathcal{S}$ reposant sur ce contour étant
      égale à $\pi r^2$. Soit un champ magnétique $\vv{B}(M)$
      #+BEGIN_SRC latex
        \begin{align*}
          B(r)\times2\pi r&=\mu_0\rho u\times\pi r^2\\
          \vv{B}(M)&=\frac{\mu_0}{2}\rho ur\vv{u}_\theta
        \end{align*}
      #+END_SRC
   3)
       #+BEGIN_SRC latex
         \begin{align*}
           \vv{F}(r=R)&=q\vv{E}(R)+q\vv{u}\times\vv{B}(R)\\
           &=\frac{q\rho}{2\epsilon_0}\vv{R}+\frac{q\mu_0\rho u^2R}{2}\vv{u_x}\times\vv{u}_theta\\
           &=\frac{q\rho}{2\epsilon_0}R\vv{u}_r-\frac{q\mu_0\rho u^2R}{2}R\vv{u}_r\text{ soit avec } \mu_0\epsilon_0c^2=1\\
           &=\frac{q\rho}{2\epsilon_0}\vv{R}\left(1-\frac{u^2}{c^2}\right)\\
           &=\frac{q\rho}{2\epsilon_0\gamma^2}\vv{R}
         \end{align*}
       #+END_SRC
       La relation $\vv{F}^\prime=\gamma\vv{F}$ implique
       #+BEGIN_SRC latex
         \begin{equation*}
           \frac{q\rho_0}{2\epsilon_0}\vv{R}=\frac{q\rho}{2\epsilon_0\gamma^2}\vv{R}
         \end{equation*}
       #+END_SRC
       soit
       #+BEGIN_SRC latex
         \begin{equation*}
           \rho=\gamma\rho_0
         \end{equation*}
       #+END_SRC
   4) Le principe fondamentale de la dynamique relativiste
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\text{d}}{\text{d}t}\left(\gamma m\vv{u}\right)&=\Upsigma\vv{F}\\
          \gamma m\frac{\text{d}\vv{u}}{\text{d}t}+m\vv{u}\frac{\text{d}\gamma}{\text{d}t}&=\vv{F}
        \end{align*}
      #+END_SRC
      or $\vv{F}\parallel\vv{u}_r$ imliquant que le second terme
      $m\vv{u}\tfrac{\text{d}\gamma}{\text{d}t}$ soit nul. Soit
      #+BEGIN_SRC latex
        \begin{align*}
          \gamma m\frac{\text{d}\vv{u}}{\text{d}t}&=\vv{F}\\
          \gamma m\ddot{R}&=\frac{q\rho}{2\epsilon_0\gamma^2}R\\
          \ddot{R}-\frac{q\rho}{2\epsilon_0m}\frac{R}{\gamma^3}&=0
        \end{align*}
      #+END_SRC
      La solution à cette équation différentielle s'écrit $R(t)=R_0\cosh\zeta t$
      où $\zeta^2=\frac{q\rho}{2\epsilon_0m\gamma^3}$.

      La variation relative de rayon $\Delta R/R_0$ devient
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}\simeq\frac{\zeta^2}{2}t^2&=\frac{q\rho}{4\epsilon_0m}\frac{1}{\gamma^3}t^2\\
          &=\frac{q\gamma\rho_0}{4\epsilon_0m}\frac{1}{\gamma^3}t^2=\frac{q\gamma\rho_0}{4\epsilon_0m}\frac{1}{\gamma^3}\frac{x^2}{u^2}\\
          &=\frac{q\rho_0}{4\epsilon_0m}\frac{x^2}{\gamma^2-1}=\left.\frac{\Delta R}{R_0}\right|_{\mathcal{R}^\prime}
        \end{align*}
      #+END_SRC
   5) L'énergie cinétique $T$ du faisceau d'électron est égale à
      $T=F.d=eE.d=eV/d.d=eV$ soit la tension accélératrice. Ainsi, une tension
      accélératrice de $V=\unit[0.1]{MV}$ fournit une énergie cinétique de
      $T=\unit[0.1]{MeV}$. Le facteur de Lorentz $\gamma$ est égale à
      $1+\tfrac{T}{mc^2}$ où $mc^2=\unit[0.511]{MeV}$. Finalement, l'intensité
      électrique du faisceau $I$ est égale au flux de la densité de courant $j$
      soit $I=j.S=\rho u.S\simeq\rho u\pi R_0^2$. La variation de la dimension
      transerve devient
      #+BEGIN_SRC latex
        \begin{equation*}
          \frac{\Delta R}{R_0}=\frac{e}{4\pi\epsilon_0mc^2}\times\frac{I}{c}\times\frac{L^2}{R_0^2}\times\frac{1}{(\gamma^2-1)^{3/2}}
        \end{equation*}
      #+END_SRC

      Applications numériques :

      $V=\unit[0.1]{MV}$, $\gamma=1.2$ \rightarrow $\frac{\Delta R}{R_0}=0.5=50\%$

      $V=\unit[10]{MV}$,$\gamma=21$ \rightarrow $\frac{\Delta R}{R_0}=1.5\,10^{-5}$
