#+TITLE: Correction TD Électromagnétisme
#+AUTHOR: Xavier Garrido
#+DATE: 21/01/14
#+OPTIONS: ^:{} toc:2
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER_EXTRA: \newcommand{\vv}[1]{\overrightarrow{#1}}
#+LATEX_HEADER_EXTRA: \renewcommand{\div}{\ensuremath{\text{div}}}
#+LATEX_HEADER_EXTRA: \newcommand{\rot}{\ensuremath{\vv{\text{rot}}}}

* TD1 : Électromagnétisme & relativité

** Introduction
*Transformation de Lorentz :* $\beta=\tfrac{v}{c}$ et
 $\gamma=\tfrac{1}{\surd{1-\beta^2}}$. Si $\mathcal{R}^\prime$ est en mouvement
 rectiligne uniforme selon l'axe $x$ par rapport à $\mathcal{R}$ alors
 #+BEGIN_SRC latex
   \begin{equation*}
     \begin{bmatrix}
       ct^\prime\\x^\prime\\y^\prime\\z^\prime
     \end{bmatrix}
     =
     \begin{bmatrix}
       \gamma&-\beta\gamma&0&0\\
       -\beta\gamma&\gamma&0&0\\
       0&0&1&0\\
       0&0&0&1
     \end{bmatrix}
     \cdot
     \begin{bmatrix}
       ct\\x\\y\\z
     \end{bmatrix}
   \end{equation*}
 #+END_SRC
 et la transformation inverse
 #+BEGIN_SRC latex
   \begin{equation*}
     \begin{bmatrix}
       ct\\x\\y\\z
     \end{bmatrix}
     =
     \begin{bmatrix}
       \gamma&+\beta\gamma&0&0\\
       +\beta\gamma&\gamma&0&0\\
       0&0&1&0\\
       0&0&0&1
     \end{bmatrix}
     \cdot
     \begin{bmatrix}
       ct^\prime\\x^\prime\\y^\prime\\z^\prime
     \end{bmatrix}
   \end{equation*}
 #+END_SRC

*Transformation du champ EM :*

Composantes tangentielles au déplacement
$\vv{E}^\prime_\parallel=\vv{E}_\parallel$ et
$\vv{B}^\prime_\parallel=\vv{B}_\parallel$.

Composantes normales au déplacement
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}^\prime_\perp&= \gamma\,\left(\vv{E}_\perp+\vv{v}\times\vv{B}_\perp\right)\\
    \vv{B}^\prime_\perp&= \gamma\,\left(\vv{B}_\perp-\vv{v}\times\frac{\vv{E}_\perp}{c^2}\right)
  \end{align*}
#+END_SRC
ou
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)\\
    \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)
  \end{align*}
#+END_SRC

*Remarques :*
- les "quantités" perpendiculaires au déplacement telles les longueurs ($y$ et
  $z$ dans notre cas), ne subissent pas les effets de la relativité. Autrement
  dit une longueur $y$ restera inchangée sous la transformation
  $\mathcal{R}\rightarrow\mathcal{R}^\prime$ : $y=y\prime$

** Force entre des électrons qui se déplacent côte à côte

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.7\linewidth
[[file:./figures/referentiel_relat_1.pdf]]
#+END_CENTER

1) Soit $\mathcal{R}^\prime$ le référentiel où les particules sont au repos. Le
   champ électrique exercé sur $M_2$ par $M_1$ s'écrit
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}^\prime(M_2) = \frac{q_1}{4\pi\epsilon_0}\times\frac{\vv{M_1M_2}}{M_1M_2^3}=-\frac{e}{4\pi\epsilon_0\,d^2}\vv{u}_{z^\prime}
     \end{equation*}
   #+END_SRC
   /i.e./ le champ électrique coulombien. Les particules étant au repos, il n'y
   a pas de déplacement de charge donc $\vv{B}^\prime(M_2)=\vv{0}$. La force
   (coulombienne) qui s'exerce sur l'électron en $M_2$ est
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{F}^\prime(M_2)=-e\vv{E}^\prime(M_2)-e\vv{v}\times\vv{B}^\prime(M_2)=\frac{e^2}{4\pi\epsilon_0\,d^2}\vv{u}_{z^\prime}=-\vv{F}^\prime(M_1)
     \end{equation*}
   #+END_SRC
   soit une force répulsive.

2) Dans $\mathcal{R}$, on applique les règles de transformation du champ EM soit
   $\vv{E}^\prime_\parallel=\vv{E}_\parallel=\vv{0}$ et
   $\vv{B}^\prime_\parallel=\vv{B}_\parallel=\vv{0}$. Les composantes normales
   deviennent
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)\\
       \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)
     \end{align*}
   #+END_SRC
   On déduit que
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}_\perp=\gamma\left(\vv{E}^\prime_\perp-\vv{v}\times\vv{B}^\prime_\perp\right)=\gamma\vv{E}^\prime_\perp=-\frac{\gamma e}{4\pi\epsilon_0\,d^2}\vv{u}_z
     \end{equation*}
   #+END_SRC
   sachant que $\vv{u}_z=\vv{u}_{z^\prime}$.

   Le champ magnétique $\vv{B}_\perp$ est égal à
   $\gamma\vv{v}\times\frac{\vv{E}^\prime_\perp}{c^2}$ soit
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{B}_\perp&=\frac{\gamma\,vE^\prime_\perp}{c^2}\,\vv{u}_x\times\vv{u}_z=-\frac{\gamma\,vE^\prime_\perp}{c^2}\,\vv{u}_y\\
       &=\frac{\gamma v}{c^2}\times\frac{e}{4\pi\epsilon_0\,d^2}\,\vv{u}_y\text{ avec } \mu_0\epsilon_0c^2=1\\
       &=\frac{\mu_0\gamma ve}{4\pi d^2}\vv{u}_y
     \end{align*}
   #+END_SRC
   La force résultante est égale à
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{F}(M_2)&=-e\vv{E}(M_2)-e\vv{v}\times\vv{B}(M_2)\\
       &=-e\gamma\vv{E}^\prime(M_2)+e\gamma v^2\vv{u}_x\times\vv{u_y}\frac{E^\prime(M_2)}{c^2}\\
       &=-e\gamma\vv{E}^\prime(M_2)\left[1-\frac{v^2}{c^2}\right]\text{ avec }\gamma=\frac{1}{\surd{1-v^2/c^2}}\\
       &=-e\gamma\vv{E}^\prime(M_2)\times\frac{1}{\gamma^2}=\frac{\vv{F}^\prime(M_2)}{\gamma}
     \end{align*}
   #+END_SRC
   Globalement, $F^\prime(M_2)>F(M_2)$. La force d'origine magnétique induite
   par le déplacement des particules compense l'augmentation de la force
   électrique de répulsion.

   *AN:*

   $\mathcal{E}=\gamma mc^2 - mc^2=(\gamma-1)mc^2$ donc
   $\gamma=1+\frac{\mathcal{E}}{mc^2}$. La masse de l'électron est 0.511 MeV.

   Pour $\mathcal{E}=\unit[1]{eV}$, $\gamma\sim1$
   #+BEGIN_SRC latex
     \begin{align*}
       F&=F^\prime=\frac{e^2}{4\pi\epsilon_0\,d^2}=\frac{e^2\mu_0c^2}{4\pi d^2}\\
       &=\frac{e^2c^2\times4\pi\,10^{-7}}{4\pi d^2}=\frac{(1.6\,10^{-19})^2\times(3\,10^8)^2\times10^{-7}}{(10^{-3})^2}\\
       &=\unit[2.3\,10^{-22}]{N}
     \end{align*}
   #+END_SRC

   Pour $\mathcal{E}=\unit[1]{MeV}$, $\gamma\simeq3$
   #+BEGIN_SRC latex
     \begin{align*}
       F&=\frac{F^\prime}{3}=\unit[7.7\,10^{-23}]{N}
     \end{align*}
   #+END_SRC

3) $v\rightarrow0$, $\beta\ll1$ et donc $\gamma\simeq1+\tfrac{\beta^2}{2}$
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{F}&=\frac{\vv{F}^\prime}{\gamma}\\
       &=\vv{F}^\prime\times\left(1-\beta^2\right)^{1/2}\\
       &\simeq\left(1-\tfrac{\beta^2}{2}\right)\vv{F}^\prime
     \end{align*}
   #+END_SRC
** Fil chargé
1) Dans $\mathcal{R}^\prime$, les charges électriques sont immobiles \equiv
   électrostatique. La charge électrique $Q^\prime$ se déduit de la densité
   linéique de charge $\lambda_0^\prime$
   #+BEGIN_SRC latex
     \begin{equation*}
       Q^\prime=\lambda_0^\prime\times\ell^\prime=\rho^\prime\times S^\prime\times\ell^\prime
     \end{equation*}
   #+END_SRC
   d'où $\rho^\prime=\tfrac{\lambda_0^\prime}{S^\prime}=\tfrac{\lambda_0^\prime}{S}$ car la
   surface $S$ est une quantité perpendiculaire au déplacement donc
   $S=S^\prime$.

   Les charges étant immobiles, il n'y a pas de courant d'où
   $\vv{j}^\prime=\vv{0}$ et donc pas de champ magnétique
   $\vv{B}^\prime=\vv{0}$. Le champ électrique $\vv{E}^\prime$ se déduit du
   théorème de Gauss, en évaluant au préalable, les symétries et les invariances
   de la distribution de charge. Ainsi, en coordonnées cylindriques où
   $\vv{u}_x=\vv{u}_z$, les plans $(\vv{u}_r,\vv{u}_\theta)$ et
   $(\vv{u}_r,\vv{u}_z)$ sont plans de symétrie de la distribution de charge. Le
   champ électrique résultant est donc contenu dans chacun de ces plans soit
   $\vv{E}(M) = E(M)\vv{u}_r$. Par ailleurs, la distribution de charge est
   invariante par rotation $\theta$ et par translation $x\equiv z$ donc
   $E(M)=E(r,\theta,z)=E(r)$.

   Le théorème de Gauss
   #+BEGIN_SRC latex
     \begin{equation*}
       \oiint_{\mathcal{S}}\vv{E}\cdot\text{d}\vv{S}=\frac{Q_\text{int.}}{\epsilon_0}
     \end{equation*}
   #+END_SRC
   où la surface de Gauss $\mathcal{S}$ est un cylindre de rayon $D^\prime$ et
   de hauteur $h$. En tenant compte des invariances et symétries de la
   distribution de charge, on obtient le champ $\vv{E}^\prime(M)$
   #+BEGIN_SRC latex
     \begin{equation*}
       E^\prime(M)\times2\pi D^\prime\times h = \frac{\lambda_0^\prime\times h}{\epsilon_0}
     \end{equation*}
   #+END_SRC
   soit
   #+BEGIN_SRC latex
     \begin{equation*}
       \vv{E}^\prime(M)=\frac{\lambda_0^\prime}{2\pi\epsilon_0D^\prime}\vv{u}_r
     \end{equation*}
   #+END_SRC

2) Calculs dans $\mathcal{R}$
   1) Contraction des longeurs car $L$ est colinéaire au déplacement du
      cylindre.
      #+BEGIN_SRC latex
        \begin{equation*}
          L=\frac{L^\prime}{\gamma}\text{ mais } S = S^\prime\text{ car } S,S^\prime\perp\vv{u}
        \end{equation*}
      #+END_SRC

      Invariance de la charge électrique $Q=Q^\prime$ (ce postulat n'a jamais
      été mis en défaut).
      #+BEGIN_SRC latex
        \begin{equation*}
          Q=Q^\prime=\rho^\prime\times S^\prime\times L^\prime=\rho\times S\times L
        \end{equation*}
      #+END_SRC
      d'où
      #+BEGIN_SRC latex
        \begin{equation*}
          \rho=\rho^\prime\times\frac{L^\prime}{L}=\gamma\rho^\prime
        \end{equation*}
      #+END_SRC

      Densité de courant $\vv{j}$
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{j}=\rho\cdot\vv{u}=\rho u\vv{u}_x
        \end{equation*}
      #+END_SRC

      Le 4-vecteur $\vv{J}=(\rho c,\vv{j})$ est un 4-vecteur de Lorentz si
      l'égalité
      #+BEGIN_SRC latex
        \begin{equation*}
          \begin{bmatrix}
            \rho^\prime c\\j^\prime_x\\j^\prime_y\\j^\prime_z
          \end{bmatrix}
          =
          \begin{bmatrix}
            \gamma&-\beta\gamma&0&0\\
            -\beta\gamma&\gamma&0&0\\
            0&0&1&0\\
            0&0&0&1
          \end{bmatrix}
          \cdot
          \begin{bmatrix}
            \rho c\\j_x\\j_y\\j_z
          \end{bmatrix}
        \end{equation*}
       #+END_SRC
      La distribution de courant est nulle dans $\mathcal{R}^\prime$ donc
      $j^\prime_x=j^\prime_y=j^\prime_z=0$ $j_y=j_z=0$ et
      #+BEGIN_SRC latex
        \begin{align*}
          \gamma\rho c - \beta\gamma j_x&= \gamma\rho c-\beta\gamma\rho u\\
          &=\gamma\rho c-\beta\gamma\rho u\times\frac{c}{c}\\
          &=\gamma\rho c\left(1-\beta^2\right)\\
          &=\gamma\rho c\times\frac{1}{\gamma^2}=\frac{\rho c}{\gamma}\\
          &=\rho^\prime c
        \end{align*}
      #+END_SRC
      De même,
      #+BEGIN_SRC latex
        \begin{align*}
          -\beta\gamma\rho c+\gamma j_x&=-\beta\gamma\rho c+\gamma\rho u\\
          &=-\gamma\rho u+\gamma\rho u\\
          &=0=j^\prime_x
        \end{align*}
      #+END_SRC

   2) Calcul du champ électrique $\vv{E}(M)$

      Densité volumique et linéique de charge
      $\rho=\gamma\rho^\prime\rightarrow\lambda_0=\gamma\lambda_0^\prime$ d'où
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{E}(M)=\frac{\gamma\lambda_0^\prime}{2\pi\epsilon_0\,D}\vv{u}_r
        \end{equation*}
      #+END_SRC

      Le courant dans le fil est $\text{d}I=\vv{j}.\text{d}\vv{S}$ soit
      $I=j\times S$ et le champ magnétique $\vv{B}(M)$ s'écrit (/cf./ polycopié
      page 88, Chapitre Magnétostatique)
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}(M)&=\frac{\mu_0I}{2\pi\,D}\vv{u}_\theta\\
          &=\frac{\mu_0jS}{2\pi\,D}\vv{u}_\theta
        \end{align*}
      #+END_SRC
      or $j=\rho u=\gamma\rho^\prime u=\frac{\gamma\lambda_0^\prime u}{S}$ d'où
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}(M)&=\frac{\gamma\mu_0\lambda_0^\prime u}{2\pi\,D}\vv{u}_\theta\text{ avec } \mu_0\epsilon_0c^2=1\\
          \vv{B}(M)&=\frac{\gamma u}{c^2}E^\prime(M)\vv{u}_\theta
        \end{align*}
      #+END_SRC

3) Transformation des champs
   1) Transformation du champ électrique avec $\vv{B}^\prime=\vv{0}$
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{E}_\perp&= \gamma\,\left(\vv{E}^\prime_\perp-\vv{u}\times\vv{B}^\prime_\perp\right)\\
          \vv{E}(M)&= \gamma\,\vv{E}^\prime(M)\text{ vrai } \vv{E}(M)=\frac{\gamma\lambda_0^\prime}{2\pi\epsilon_0\,D}\vv{u}_r
        \end{align*}
      #+END_SRC

      Transformation du champ magnétique
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{B}_\perp&= \gamma\,\left(\vv{B}^\prime_\perp+\vv{u}\times\frac{\vv{E}^\prime_\perp}{c^2}\right)\\
          \vv{B}(M)&=\gamma u\frac{E^\prime(M)}{c^2}\vv{u}_x\times\vv{u}_r\\
          &=\frac{\gamma u}{c^2}E^\prime(M)\vv{u}_\theta
        \end{align*}
      #+END_SRC

   2) $\vv{E}^\prime.\vv{B}^\prime=0$ et
      $\vv{E}.\vv{B}=\frac{\gamma^2u}{c^2}E^{\prime2}\,\vv{u}_\theta.\vv{u}_r=0$
   3)
      #+BEGIN_SRC latex
        \begin{align*}
          E^2-B^2c^2 &= (\gamma E^\prime)^2 - \left(\frac{\gamma u}{c^2}\right)^2E^{\prime2}c^2\\
          &=(\gamma E^\prime)^2\left(1-\frac{u^2}{c^2}\right)=E^{\prime2}\\
          &=E^{\prime2}-B^{\prime2}c^2\text{ puisque }B^\prime=0
        \end{align*}
      #+END_SRC
** Particule chargée dans un champ magnétique uniforme
1) L'impulsion relativiste s'écrit $\vv{p}=\gamma m\vv{v}$, l'énergie totale
   étant égale à $\mathcal{E}=\gamma mc^2$. Le principe fondamental de la
   dynamique devient
   #+BEGIN_SRC latex
     \begin{align*}
       \frac{d\vv{p}}{dt}&=\Upsigma\vv{F}\\
       \frac{d}{dt}(\gamma m\vv{v})&=q\vv{v}\times\vv{B}
     \end{align*}
   #+END_SRC

   L'énergie totale $\mathcal{E}$ est égale à la variation temporelle de
   puissance $\tfrac{d\mathcal{P}}{dt}$. Or
   #+BEGIN_SRC latex
     \begin{align*}
       \mathcal{P}&=\vv{F}_\text{magnétique}.\vv{v}\\
       &=(q\vv{v}\times\vv{B}).\vv{v}\\
       &=0
     \end{align*}
   #+END_SRC
   L'énergie $\mathcal{E}$ est donc constante \rightarrow $v=v_0$ et
   $\gamma=\tfrac{1}{\surd{1-v_0^2/c^2}}$. L'équation du mouvement devient
   #+BEGIN_SRC latex
     \begin{align*}
       \gamma m\frac{d\vv{v}}{dt}&=q\vv{v}\times\vv{B}
     \end{align*}
   #+END_SRC
   soit, au facteur $\gamma$ près, identique à l'équation du mouvement pour une
   particule non-relativiste. La pulsation $\omega=\tfrac{qB}{m\gamma}$ est
   inférieure à la pulsation classique d'un cyclotron
   $\omega_c=\tfrac{qB}{m}$. La trajectoire est alors circulaire autour du champ
   magnétique $\vv{B}$ et de rayon $R=\gamma\tfrac{mv_0}{qB}$.

2) L'accélération dans le cas d'un mouvement uniforme circulaire est
   l'accélération centripète d'expression
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{a}=\frac{d\vv{v}}{dt}=-\frac{v_0^2}{R}\vv{u}_r
     \end{align*}
   #+END_SRC
   Le produit vectoriel $\vv{v}\times\vv{a}$ devient
   #+BEGIN_SRC latex
     \begin{align*}
       \vv{v}\times\vv{a}=v_0\vv{u}_\theta\times-\frac{v_0^2}{R}\vv{u}_r=\frac{v_0^3}{R}\vv{u}_z
     \end{align*}
   #+END_SRC
   La puissance rayonnée $\mathcal{P}_r$ se réduit à
   #+BEGIN_SRC latex
     \begin{align*}
       \mathcal{P}_r&=\frac{q^2\gamma^6}{6\pi\epsilon_0c^3}\left[\vv{a}^2-\left(\frac{1}{c}\vv{v}\times\vv{a}\right)^2\right]\\
       &=\frac{q^2\gamma^6}{6\pi\epsilon_0c^3}\left[\frac{v_0^4}{R^2}-\frac{v_0^6}{R^2c^2}\right]\\
       &=\frac{q^2\gamma^6}{6\pi\epsilon_0c^3}\times\frac{v_0^4}{R^2}\left[1-\frac{v_0^2}{c^2}\right]\text{ avec } \frac{1}{\gamma^2}=1-\frac{v_0^2}{c^2}\\
       &=\frac{q^2\gamma^4}{6\pi\epsilon_0c^3}\times\frac{v_0^4}{R^2}=\text{constante}
     \end{align*}
   #+END_SRC
   et l'énergie rayonnée par tour $\mathcal{E}_r=\mathcal{P}_r\times T$ avec
   $T=\tfrac{2\pi R}{v_0}$ devient
   #+BEGIN_SRC latex
     \begin{align*}
       \mathcal{E}_r&=\frac{q^2\gamma^4}{6\pi\epsilon_0c^3}\times\frac{v_0^4}{R^2}\times\frac{2\pi R}{v_0}\\
       &=\frac{q^2\gamma^4}{3\epsilon_0R}\times\frac{v_0^3}{c^3}
     \end{align*}
   #+END_SRC
   Dans la limite ultra-relativiste, $v\rightarrow c$, l'énergie rayonnée est égale à
   $\mathcal{E}_r=\frac{q^2\gamma^4}{3\epsilon_0R}$.

   *Application numérique :*

   Le faisceau de particules est constitué d'électrons de masse
   $mc^2=\unit[0.511]{MeV}$. Le facteur de Lorentz $\gamma$ se déduit de l'énergie
   totale $\mathcal{E}=\unit[6]{GeV}$
   #+BEGIN_SRC latex
     \begin{equation*}
       \gamma=\frac{\mathcal{E}}{mc^2}=12\,000\text{ soit }\frac{v}{c}=0.999999996527\simeq1
     \end{equation*}
   #+END_SRC
   L'énergie rayonnée exprimée en eV est alors égale à
   #+BEGIN_SRC latex
     \begin{align*}
       \left.\mathcal{E}_r\right|_\text{eV}&=\frac{e^2}{3\epsilon_0R}\times\gamma^4\times\frac{1}{e}\\
       &=\frac{1.6\,10^{-19}}{3\times8.85\,10^{-12}\times134}\times(12000)^4\\
       &=\frac{1.6\times(1.2)^4}{3\times8.85\times1.34}\times\unit[10^{7}]{eV}\\
       &=\unit[0.93]{MeV}=1.55\,10^{-4}\mathcal{E}
     \end{align*}
   #+END_SRC

3) Les pertes d'énergie induites par le rayonnement ont pour conséquence une
   diminution de l'énergie totale $\mathcal{E}=\gamma mc^2$ : les particules
   perdent de la vitesse. La variation d'énergie $d\mathcal{E}$ est égale à
   $-\mathcal{P}_r\,dt$ soit une variation du facteur de Lorentz $\gamma$
   #+BEGIN_SRC latex
     \begin{align*}
       mc^2d\gamma&=-\mathcal{P}_rdt\\
       \frac{d\gamma}{dt}&=-\mathcal{P}_r\times\frac{1}{mc^2}\\
       &=-\frac{q^2\gamma^4}{6\pi\epsilon_0c^3}\times\frac{v^4}{R^2}\times\frac{1}{mc^2}
     \end{align*}
   #+END_SRC
   En supposant la trajectoire toujours circulaire de rayon
   $R=\gamma\tfrac{mv}{qB}=\tfrac{\gamma v}{\omega_c}$
   #+BEGIN_SRC latex
     \begin{align*}
       \frac{d\gamma}{dt}&=-\frac{q^2\gamma^4}{6\pi\epsilon_0c^3}\times\frac{v^4}{R^2}\times\frac{1}{mc^2}\\
       &=-\frac{q^2\gamma^4}{6\pi\epsilon_0c^3}\times\frac{v^4\omega_c^2}{\gamma^2v^2}\times\frac{1}{mc^2}\\
       &=-\frac{q^2\omega_c^2}{6\pi\epsilon_0c^3}\times\frac{1}{mc^2}\times\gamma^2v^2\\
     \end{align*}
   #+END_SRC
   or $\gamma^2v^2=c^2(\gamma^2-1)$ d'où
   #+BEGIN_SRC latex
     \begin{align*}
       \frac{d\gamma}{dt}&=-\frac{q^2\omega_c^2}{6\pi\epsilon_0mc^3}\times\left(\gamma^2-1\right)\\
       \frac{d\gamma}{\gamma^2-1}&=-\frac{dt}{\tau}\text{ avec }\tau=\frac{6\pi\epsilon_0mc^3}{q^2\omega_c^2}
     \end{align*}
   #+END_SRC
   En intégrant l'équation précédente, on obtient
   #+BEGIN_SRC latex
     \begin{align*}
       \frac{d\gamma}{\gamma^2-1}&=-\frac{dt}{\tau}\\
       \frac{d\gamma}{1-\gamma^2}&=\frac{dt}{\tau}\\
       \frac{d\gamma}{1+\gamma}+\frac{d\gamma}{1-\gamma}&=2\frac{dt}{\tau}\\
       \ln(\gamma+1)-\ln(\gamma-1)&=\frac{2t}{\tau}+\text{constante}\\
       \ln\frac{\gamma+1}{\gamma-1}&=\frac{2t}{\tau}+\text{constante}\\
       \frac{\gamma+1}{\gamma-1}&=Ke^{\tfrac{2t}{\tau}}
     \end{align*}
   #+END_SRC
   où, à $t=0,\gamma=\gamma_0=\tfrac{1}{\surd{1-v_0^2/c^2}}$,
   $K=\frac{\gamma_0+1}{\gamma_0-1}$. On obtient ainsi
   #+BEGIN_SRC latex
     \begin{align*}
       \gamma&=\frac{Ke^{\tfrac{2t}{\tau}}+1}{Ke^{\tfrac{2t}{\tau}}-1}\\
       &=\frac{K+e^{-\tfrac{2t}{\tau}}}{K-e^{-\tfrac{2t}{\tau}}}
     \end{align*}
   #+END_SRC
   et
   #+BEGIN_SRC latex
     \begin{align*}
       \mathcal{E}=\gamma mc^2=\frac{Ke^{\tfrac{2t}{\tau}}+1}{Ke^{\tfrac{2t}{\tau}}-1}\times mc^2
     \end{align*}
   #+END_SRC

   Lorsque $t\rightarrow\infty$, $\gamma\simeq\frac{K}{K}=1$ et l'énergie totale
   $\mathcal{E}$ est alors uniquement l'énergie de masse de la particule, la
   vitesse et donc l'énergie cinétique sont nulles.

   Le rayon $R$, proportionnel à $\gamma v$, diminue en fonction du
   temps. Ainsi, la trajectoire demeure circulaire à chaque instant $t$ mais
   avec un rayon de courbure chaque fois plus faible en raison des pertes
   d'énergie par rayonnement. Les particules décrivent une spirale.

   #+BEGIN_SRC latex
     \centering
     \begin{tikzpicture}[scale=0.95]
       \draw [,domain=0:25.1327,variable=\t,smooth,samples=75]
       plot ({\t r}: {0.002*\t*\t});
     \end{tikzpicture}
   #+END_SRC

** Particule chargée dans des champs électrique et magnétique perpendiculaires

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.7\linewidth
[[file:./figures/referentiel_relat_4.pdf]]
#+END_CENTER

Soit $\vv{E}=E\vv{u}_y$ et $\vv{B}=B\vv{u}_z$ avec $Bc>E$. Le référentiel
$\mathcal{R}^\prime$ doit être tel que $\vv{E}^\prime=\vv{0}$ soit
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}^\prime_\parallel&=\vv{E}_\parallel=\vv{0}\\
    \vv{E}^\prime_\perp&=\gamma\left(\vv{E}_\perp+\vv{u}\times\vv{B}_\perp\right)=\vv{0}
  \end{align*}
#+END_SRC

La première condition est vérifiée du fait que $\vv{E}$ est orthogonal au
vecteur déplacement $\vv{u}$. La seconde condition est vérifiée si
#+BEGIN_SRC latex
  \begin{align*}
    \vv{E}+\vv{u}\times\vv{B}&=\vv{0}\\
    E\vv{u}_y + uB\,\vv{u}_x\times\vv{u}_z&=\vv{0}\\
    E-Bu&=0\\
    u&=\frac{E}{B}
  \end{align*}
#+END_SRC

Pour obtenir un champ électrique nul dans le référentiel $\mathcal{R}^\prime$,
il faut donc que la vitesse de déplacement $u$ du référentiel $\mathcal{R}^\prime$
par rapport au référentiel $\mathcal{R}$ soit égale au rapport du champ
électrique $E$ sur le champ magnétique $B$. La vitesse ainsi obtenue est, par
ailleurs, inférieure à $c$ du fait que $Bc>E$.

Calcul du champ magnétique $\vv{B}^\prime$ :
#+BEGIN_SRC latex
  \begin{align*}
    \vv{B}^\prime_\parallel&=\vv{B}_\parallel=\vv{0}\\
    \vv{B}^\prime_\perp&=\gamma_e\left(\vv{B}_\perp-\vv{u}\times\frac{\vv{E}_\perp}{c^2}\right)\\
    &=\gamma_e\left(B\vv{u}_z-\frac{uE}{c^2}\vv{u}_x\times\vv{u}_y\right)\\
    &=\gamma_e\left(B\vv{u}_z-\frac{u^2}{c^2}B\vv{u}_z\right)\\
    &=\frac{\vv{B}}{\gamma_e}
  \end{align*}
#+END_SRC

La force de Lorentz $\vv{F}^\prime$ qui s'applique à la particule de charge $q$
est purement magnétique $q\vv{v}\times\vv{B}^\prime$. Le principe fondamental de
la dynamique $\vv{F}^\prime=q\vv{v}\times\vv{B}=m\vv{a}$ se traduit par un
trajectoire circulaire de rayon $R$
#+BEGIN_SRC latex
  \begin{equation*}
    \frac{v^2}{R}=\frac{qvB^\prime}{m}\rightarrow R=\frac{mv}{qB^\prime}=\frac{\gamma_emv}{qB}
  \end{equation*}
#+END_SRC

** Étude de la charge d'espace

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.7\linewidth
[[file:./figures/referentiel_relat_3.pdf]]
#+END_CENTER
À $t=t^\prime=0$, $R=R_0$, $\dot{R}=\dot{R}^\prime=0$ et $\dot{\theta}=0$

1) dans $\mathcal{R}^\prime$, $\rho_0=$ constante
   1) Champ électrique $\vv{E}^\prime(M)$

      Les plans $(\vv{u}_r,\vv{u}_\theta)$ et $(\vv{u}_r,\vv{u}_{x^\prime})$
      sont des plans de symétrie de la distribution de charge \rightarrow le
      champ électrique appartient donc à chacun des plans :
      $\vv{E}^\prime(M)=E(M)\vv{u}_r$. De plus, il y a invariance par
      translation selon l'axe $x^\prime$ et par rotation d'angle \theta :
      $\vv{E}^\prime(M)=E(r)\vv{u}_r$.

      Théorème de Gauss :
      #+BEGIN_SRC latex
        \begin{equation*}
          \oiint_\mathcal{S}\vv{E}^\prime(M)\cdot\text{d}\vv{S}=\frac{Q_\text{int.}}{\epsilon_0}
        \end{equation*}
      #+END_SRC
      où la surface de Gauss est un cylindre de rayon $r<R$ et de hauteur $h$.
      #+BEGIN_SRC latex
        \begin{align*}
          E^\prime(r)\times2\pi r\times h&=\frac{\rho_0}{\epsilon_0}\times h\times\pi r^2\\
          \vv{E}^\prime(M)&=\frac{\rho_0r}{2\epsilon_0}\vv{u}_r=\frac{\rho_0}{2\epsilon_0}\vv{r}
        \end{align*}
      #+END_SRC

      Au voisinage de $r\sim R$, la force subie par une particule de charge $q$
      devient
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{F}^\prime=q\vv{E}^\prime(R)=\frac{q\rho_0}{2\epsilon_0}\vv{R}
        \end{equation*}
      #+END_SRC
      soit une force répulsive.
   2) Mécanique classique ou Newtonienne $\Upsigma\vv{F}=m\vv{a}$ [fn:1]
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{F}^\prime&=m\vv{a}=m\ddot{R}\vv{u}_r=m\frac{\text{d}^2R}{\text{d}t^{\prime2}}\vv{u}_r\\
          \frac{q\rho_0}{2\epsilon_0}R\vv{u}_r&=m\ddot{R}\vv{u}_r\rightarrow\ddot{R}-\frac{q\rho_0}{2m\epsilon_0}R=0
        \end{align*}
      #+END_SRC
      Solutions du type $R(t^\prime)=Ae^{\alpha t^\prime}+Be^{-\alpha t^\prime}$
      où $\alpha^2=\tfrac{q\rho_0}{2m\epsilon_0}$. Or à $t^\prime=0$, $R=R_0$ et
      $\dot{R}=0$ d'où $A\alpha-B\alpha=0\rightarrow A=B$ et $A+B=R_0\rightarrow
      A=\tfrac{R_0}{2}$. La solution de l'équation différentielle est ainsi
      #+BEGIN_SRC latex
        \begin{equation*}
          R(t^\prime)=\frac{R_0}{2}e^{\alpha t^\prime}+\frac{R_0}{2}e^{-\alpha t^\prime}=R_0\cosh\alpha t^\prime
        \end{equation*}
      #+END_SRC
      On suppose que le mouvement transverse /i.e./ $R(t^\prime)$ est lent soit
      $\alpha t^\prime\ll1$. Le cosinus hyperbolique se réduit ainsi à
      $\cosh\alpha t^\prime\simeq1+\tfrac{(\alpha t^\prime)^2}{2}$. On déduit
      ainsi la variation relative de $R$
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}=\frac{R-R_0}{R_0}=\frac{R}{R_0}-1\simeq1+\frac{(\alpha t^\prime)^2}{2}-1&=\frac{\alpha^2}{2}t^{\prime2}\\
          &=\frac{q\rho_0}{4\epsilon_0m}t^{\prime2}
        \end{align*}
      #+END_SRC
   3) Dilatation du temps /i.e./ $t=\gamma t^\prime$ et $x=ut$ soit
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}=\frac{q\rho_0}{4\epsilon_0m}\frac{t^2}{\gamma^2}&=\frac{q\rho_0}{4\epsilon_0m}\times\frac{x^2}{\gamma^2u^2}\times\frac{c^2}{c^2}\\
          &=\frac{q\rho_0}{4\epsilon_0mc^2}\times\frac{x^2}{\gamma^2\beta^2}\text{ or }\gamma^2=\tfrac{1}{1-\beta^2},\gamma^2\beta^2=\gamma^2-1\\
          &=\frac{q\rho_0}{4\epsilon_0mc^2}\times\frac{x^2}{\gamma^2-1}
        \end{align*}
      #+END_SRC
2)
   1) Le champ électrique obéit aux mêmes règles d'invariance et de symétries
      que dans le référentiel $\mathcal{R}^\prime$ soit
      $\vv{E}(M)=E(r)\vv{u}_r$. Concernant le champ magnétique $\vv{B}(M)$, la
      densité de courant $\vv{j}=\rho\vv{u}$ est colinéaire à $\vv{u}_x$ et donc
      le plan $(\vv{u}_r,\vv{u}_x)$ est un plan de symétrie de la distribution
      de courant \rightarrow le champ magnétique est donc normal à ce plan soit
      $\vv{B}(M)=B(M)\vv{u}_\theta$. Par ailleurs, les mêmes règles d'invariance
      s'appliquent au champ magnétique : $\vv{B}(M)=B(r)\vv{u}_\theta$.
   2) Le calcul des champs électrique et magnétique se fait /via/ respectivement
      le théorème de Gauss et le théorème d'Ampère. Le champ électrique est
      ainsi
      #+BEGIN_SRC latex
        \begin{equation*}
          \vv{E}(M)=\frac{\rho}{2\epsilon_0}\vv{r}
        \end{equation*}
      #+END_SRC

      Le théorème d'Ampère :
      #+BEGIN_SRC latex
        \begin{equation*}
          \oint_{\mathcal{C}}\vv{B}.\text{d}\vv{\ell}=\oiint_\mathcal{S}\mu_0\vv{j}.\text{d}\vv{S}\text{ avec} \vv{j}=\rho u\vv{u}_x
        \end{equation*}
      #+END_SRC
      Le contour $\mathcal{C}$ est donc une boucle de rayon $r$ orientée suivant
      $\vv{u}_\theta$, la surface $\mathcal{S}$ reposant sur ce contour étant
      égale à $\pi r^2$. Soit un champ magnétique $\vv{B}(M)$
      #+BEGIN_SRC latex
        \begin{align*}
          B(r)\times2\pi r&=\mu_0\rho u\times\pi r^2\\
          \vv{B}(M)&=\frac{\mu_0}{2}\rho ur\vv{u}_\theta
        \end{align*}
      #+END_SRC
   3)
       #+BEGIN_SRC latex
         \begin{align*}
           \vv{F}(r=R)&=q\vv{E}(R)+q\vv{u}\times\vv{B}(R)\\
           &=\frac{q\rho}{2\epsilon_0}\vv{R}+\frac{q\mu_0\rho u^2R}{2}\vv{u_x}\times\vv{u}_\theta\\
           &=\frac{q\rho}{2\epsilon_0}R\vv{u}_r-\frac{q\mu_0\rho u^2R}{2}R\vv{u}_r\text{ soit avec } \mu_0\epsilon_0c^2=1\\
           &=\frac{q\rho}{2\epsilon_0}\vv{R}\left(1-\frac{u^2}{c^2}\right)\\
           &=\frac{q\rho}{2\epsilon_0\gamma^2}\vv{R}
         \end{align*}
       #+END_SRC
       La relation $\vv{F}^\prime=\gamma\vv{F}$ implique
       #+BEGIN_SRC latex
         \begin{equation*}
           \frac{q\rho_0}{2\epsilon_0}\vv{R}=\frac{q\rho}{2\epsilon_0\gamma^2}\vv{R}
         \end{equation*}
       #+END_SRC
       soit
       #+BEGIN_SRC latex
         \begin{equation*}
           \rho=\gamma\rho_0
         \end{equation*}
       #+END_SRC
   4) Le principe fondamental de la dynamique en relativité
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\text{d}}{\text{d}t}\left(\gamma m\vv{u}\right)&=\Upsigma\vv{F}\\
          \gamma m\frac{\text{d}\vv{u}}{\text{d}t}+m\vv{u}\frac{\text{d}\gamma}{\text{d}t}&=\vv{F}
        \end{align*}
      #+END_SRC
      or $\vv{F}\parallel\vv{u}_r$ impliquant que le second terme
      $m\vv{u}\tfrac{\text{d}\gamma}{\text{d}t}$ soit nul. Soit
      #+BEGIN_SRC latex
        \begin{align*}
          \gamma m\frac{\text{d}\vv{u}}{\text{d}t}&=\vv{F}\\
          \gamma m\ddot{R}&=\frac{q\rho}{2\epsilon_0\gamma^2}R\\
          \ddot{R}-\frac{q\rho}{2\epsilon_0m}\frac{R}{\gamma^3}&=0
        \end{align*}
      #+END_SRC
      La solution de cette équation différentielle s'écrit $R(t)=R_0\cosh\zeta t$
      où $\zeta^2=\frac{q\rho}{2\epsilon_0m\gamma^3}$.

      La variation relative de rayon $\Delta R/R_0$ devient
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\Delta R}{R_0}\simeq\frac{\zeta^2}{2}t^2&=\frac{q\rho}{4\epsilon_0m}\frac{1}{\gamma^3}t^2\\
          &=\frac{q\gamma\rho_0}{4\epsilon_0m}\frac{1}{\gamma^3}t^2=\frac{q\gamma\rho_0}{4\epsilon_0m}\frac{1}{\gamma^3}\frac{x^2}{u^2}\\
          &=\frac{q\rho_0}{4\epsilon_0m}\frac{x^2}{\gamma^2-1}=\left.\frac{\Delta R}{R_0}\right|_{\mathcal{R}^\prime}
        \end{align*}
      #+END_SRC
   5) L'énergie cinétique $T$ du faisceau d'électron est égale à
      $T=F.d=eE.d=eV/d.d=eV$ soit la tension accélératrice. Ainsi, une tension
      accélératrice de $V=\unit[0.1]{MV}$ fournit une énergie cinétique de
      $T=\unit[0.1]{MeV}$. Le facteur de Lorentz $\gamma$ est égale à
      $1+\tfrac{T}{mc^2}$ où $mc^2=\unit[0.511]{MeV}$. Finalement, l'intensité
      électrique du faisceau $I$ est égale au flux de la densité de courant $j$
      soit $I=j.S=\rho u.S\simeq\rho u\pi R_0^2$. La variation de la dimension
      transerve devient
      #+BEGIN_SRC latex
        \begin{equation*}
          \frac{\Delta R}{R_0}=\frac{e}{4\pi\epsilon_0mc^2}\times\frac{I}{c}\times\frac{L^2}{R_0^2}\times\frac{1}{(\gamma^2-1)^{3/2}}
        \end{equation*}
      #+END_SRC

      *Applications numériques :*

      $V=\unit[0.1]{MV}$, $\gamma=1.2$ \rightarrow $\frac{\Delta R}{R_0}=0.5=50\%$

      $V=\unit[10]{MV}$,$\gamma=21$ \rightarrow $\frac{\Delta R}{R_0}=1.5\,10^{-5}$

* TD2 : Équations de Maxwell dans le vide et champ électromagnétique
** "Propriétés mécaniques" du champ électromagnétique
1) *Énergie*
   1) Force de Lorentz : $\vv{F}=q\vv{E}+q\vv{v}\times\vv{B}$

      Équations de Maxwell :
      | Maxwell-Gauss                   | $\div\vv{E}=\vv{\nabla}.\vv{E}=\tfrac{\rho}{\epsilon_0}$                    |
      | Conservation du flux magnétique | $\div\vv{B}=\vv{\nabla}.\vv{B}=0$                                           |
      | Maxwell-Faraday                 | $\rot.\vv{E}=-\tfrac{\partial\vv{B}}{\partial t}$                           |
      | Maxwell-Ampère                  | $\rot.\vv{B}=\mu_0\vv{j}+\mu_0\epsilon_0\tfrac{\partial\vv{E}}{\partial t}$ |

   2) Équation locale de conservation de la charge
      #+BEGIN_SRC latex
        \begin{align*}
          \div\left(\rot.\vv{B}\right)=\vv{\nabla}.\left(\vv{\nabla}\times\vv{B}\right)&=0\\
          \mu_0\div\vv{j}+\mu_0\epsilon_0\frac{\partial}{\partial t}\div\vv{E}&=0\\
          \div\vv{j}+\frac{\partial\rho}{\partial t}=0
        \end{align*}
      #+END_SRC

   3) La puissance $\mathcal{P}$ s'écrit comme le produit de la force $\vv{F}$ par la
      vitesse de la particule\nbsp$\vv{v}$ :
      #+BEGIN_SRC latex
        \begin{equation*}
          \mathcal{P}=\vv{F}.\vv{v}=q\vv{E}.\vv{v}+q(\vv{v}\times\vv{B}).\vv{v}=q\vv{E}.\vv{v}
        \end{equation*}
      #+END_SRC
      La puissance par unité de volume
      $\tfrac{d\mathcal{P}}{d\tau}=nq\vv{E}.\vv{v}$ or $\vv{j}=nq\vv{v}$ d'où
      $\tfrac{d\mathcal{P}}{d\tau}=\vv{j}.\vv{E}$

   4) $\vv{R}=\tfrac{\vv{E}\times\vv{B}}{\mu_0}$ et
      $u=\tfrac{\epsilon_0E^2}{2}+\tfrac{B^2}{2\mu_0}$
      #+BEGIN_SRC latex
        \begin{align*}
          \div\vv{R}&=\frac{1}{\mu_0}\div\left(\vv{E}\times\vv{B}\right)\text{ avec }\div\left(\vv{a}\times\vv{b}\right)=\vv{b}.\rot\vv{a}-\vv{a}.\rot\vv{b}\\
          &=\frac{1}{\mu_0}\left(\vv{B}.\rot\vv{E}-\vv{E}.\rot\vv{B}\right)\\
          &=\frac{1}{\mu_0}\left(\vv{B}\times-\frac{\partial\vv{B}}{\partial t}-\vv{E}\left(\mu_0\vv{j}+\mu_0\epsilon_0\frac{\partial\vv{E}}{\partial t}\right)\right)\\
          &=\frac{1}{\mu_0}\left(-\frac{1}{2}\frac{\partial B^2}{\partial t}-\frac{\mu_0\epsilon_0}{2}\frac{\partial E^2}{\partial t}-\mu_0\vv{j}.\vv{E}\right)\\
          &=-\frac{\partial u}{\partial t}-\vv{j}.\vv{E}
        \end{align*}
        \begin{align*}
          \div\vv{R}+\frac{\partial u}{\partial t}+\vv{j}.\vv{E}=0
        \end{align*}
      #+END_SRC

   5) $\vv{E}=\vv{E}_0\cos\omega t$, $\vv{B}=\vv{B_0}\sin\omega t$
      #+BEGIN_SRC latex
        \begin{align*}
          \iiint_V\div\vv{R}d\tau+\iiint_V\frac{\partial u}{\partial t}d\tau+\iiint_V\vv{j}.\vv{E}d\tau=0\\
          \iiint_V\div\vv{R}d\tau+\iiint_V\frac{\partial u}{\partial t}d\tau+\underbrace{\iiint_V\frac{d\mathcal{P}}{d\tau}d\tau}_{\mathcal{P}_{\text{EM}\rightarrow\,q}}=0\\
        \end{align*}
      #+END_SRC
      En appliquant le théorème d'Ostrogradsky
      $\oiint_S\vv{a}.d\vv{S}=\iiint_V\div\vv{a}d\tau$, on obtient
      #+BEGIN_SRC latex
        \begin{align*}
          \oiint_S\vv{R}.d\vv{S}+\iiint_V\frac{\partial u}{\partial t}d\tau+\mathcal{P}_{\text{EM}\rightarrow\,q}=0
        \end{align*}
      #+END_SRC
      La puissance moyenne sortante devient
      #+BEGIN_SRC latex
        \begin{align*}
          \left\langle\oiint_S\vv{R}.d\vv{S}\right\rangle_T+\left\langle\iiint_V\frac{\partial u}{\partial t}d\tau\right\rangle_T+\left\langle\mathcal{P}_{\text{EM}\rightarrow\,q}\right\rangle_T=0\\
          \left\langle\mathcal{P}_\text{sortant}\right\rangle_T+\iiint_V\left\langle\frac{\partial u}{\partial t}d\tau\right\rangle_T+\left\langle\mathcal{P}_{\text{EM}\rightarrow\,q}\right\rangle_T=0
        \end{align*}
      #+END_SRC
      Or
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{\partial u}{\partial t}&=\frac{\epsilon_0E_0^2}{2}\times2\cos\omega t\sin\omega t+\frac{B_0^2}{2\mu_0}\times2\cos\omega t\sin\omega t\\
          \left\langle\frac{\partial u}{\partial t}\right\rangle_T&=\epsilon_0E_0^2\left\langle\sin2\omega t\right\rangle_T+\frac{1}{\mu_0}B_0^2\left\langle\sin2\omega t\right\rangle_T\\
          \left\langle\frac{\partial u}{\partial t}\right\rangle_T&=0
        \end{align*}
      #+END_SRC
      soit
      #+BEGIN_SRC latex
        \begin{align*}
          \left\langle\mathcal{P}_\text{sortant}\right\rangle_T+\left\langle\mathcal{P}_{\text{EM}\rightarrow\,q}\right\rangle_T=0\\
          \left\langle\mathcal{P}_\text{entrant}\right\rangle_T=\left\langle\mathcal{P}_{\text{EM}\rightarrow\,q}\right\rangle_T
        \end{align*}
      #+END_SRC

2) *Impulsion*

   #+BEGIN_CENTER
   #+ATTR_LATEX: :width 0.6\linewidth
   [[file:onde_plane.pdf]]
   #+END_CENTER

   Onde plane progressive $\vv{B}=\tfrac{\vv{u}_z\times\vv{E}}{c}$

   1)
            #+BEGIN_SRC latex
              \begin{align*}
                \mathcal{P}&=\frac{dW}{dt}\text{ avec }\mathcal{P}=q\vv{E}.\vv{v}\\
                W&=\int_0^Tq\vv{E}.\vv{v}dt
              \end{align*}
            #+END_SRC

   2) La variation d'impulsion $\vv{p}$ par unité de temps est égale à la force
      de Lorentz $\vv{F}$
      #+BEGIN_SRC latex
        \begin{align*}
          \frac{d\vv{p}}{dt}=\vv{F}
        \end{align*}
      #+END_SRC
      d'où
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{p}&=\int_0^T\vv{F}dt=\int_0^Tq\left(\vv{E}+\vv{v}\times\vv{B}\right)dt\\
          &=\int_0^Tq\vv{E}dt+\int_0^Tq\vv{v}\times\left(\frac{\vv{u}_z\times\vv{E}}{c}\right)dt
        \end{align*}
      #+END_SRC
      La première intégrale est nulle car $\vv{E}=\vv{E}_0\cos\omega t$. Pour
      déterminer l'expression de la seconde intégrale, on utilise la formule
      ci-dessous
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{a}\times\left(\vv{b}\times\vv{c}\right)=\left(\vv{a}.\vv{c}\right)\vv{b}-\left(\vv{a}.\vv{b}\right)\vv{c}
        \end{align*}
      #+END_SRC
      L'impulsion $\vv{p}$ devient
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{p}&=\int_0^T\frac{q}{c}\left(\vv{v}.\vv{E}\right)\vv{u}_z\,dt-\int_0^T\frac{q}{c}\left(\vv{v}.\vv{u}_z\right)\vv{E}dt
        \end{align*}
      #+END_SRC
      or $\vv{v}.\vv{u}_z=0$ car la particule est maintenue dans le plan
      $z=0$. L'expression de l'impulsion se réduit donc
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{p}=\int_0^T\frac{q}{c}\left(\vv{v}.\vv{E}\right)\vv{u}_z\,dt=\frac{W}{c}\vv{u}_z
        \end{align*}
      #+END_SRC

   3) L'énergie d'un photon $E=h\nu=\tfrac{hc}{\lambda}$ est égale à $pc$ /via/
      la relation de de Broglie reliant onde et matière $\lambda=\tfrac{h}{p}$

3) *Moment cinétique* $\vv{\sigma}_0=\vv{r}\times\vv{p}=\vv{OM}\times\vv{p}$ et
   $\sigma_z=\vv{\sigma}_0.\vv{u}_z$
   1) $[\sigma_z]=[L]\times[M][L][T^{-1}]=[M]\times[L^2]\times[T^{-1}]$ et
      $[W]=[M][L^2][T^{-2}]$ d'où
      #+BEGIN_SRC latex
        \begin{align*}
          [W]&=\frac{[\sigma_z]}{[T]}\\
          W&=k\frac{\sigma_z}{T}
        \end{align*}
      #+END_SRC
   2) $\vv{p}=\tfrac{W}{c}\vv{u}_z$
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{\sigma}_O&=\vv{OM}\times\vv{p}=\vv{OM}\times\frac{W}{c}\vv{u}_z\\
          \vv{\sigma}_A&=\vv{AM}\times\vv{p}=\underbrace{\vv{AO}}_{\parallel\vv{u}_z}\times\frac{W}{c}\vv{u}_z+\vv{OM}\times\frac{W}{c}\vv{u}_z\\
          &=\vv{\sigma}_O=\vv{\sigma}
        \end{align*}
      #+END_SRC
   3) Expression de $\sigma_z$
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{\sigma}&=\vv{OM}\times\vv{p}\text{ or }\frac{d\vv{p}}{dt}=\vv{F}=q\vv{E}+q\vv{v}\times\vv{B}+\vv{F}_\text{ext.}\\
          d\vv{\sigma}&=\vv{OM}\times d\vv{p}\\
          d\sigma_z&=d\vv{\sigma}.\vv{u}_z\\
          \sigma_z&=\left[\underbrace{\int_0^T\vv{OM}\times q\vv{E}dt}_{\text{\ding{192}}}+\underbrace{\int_0^T\vv{OM}\times q(\vv{v}\times\vv{B})dt}_{\text{\ding{193}}}+\underbrace{\int_0^T\vv{OM}\times\vv{F}_\text{ext.}\,dt}_{\text{\ding{194}}}\right].\vv{u}_z
        \end{align*}
      #+END_SRC

      Calcul de \ding{192}
      #+BEGIN_SRC latex
        \begin{align*}
          \text{\ding{192}}&=q\int_0^T\left(\vv{OM}\times\vv{E}\right).\vv{u}_z\,dt\\
          &=q\int_0^T\left(\vv{E}\times\vv{u}_z\right).\vv{OM}\,dt\\
          &=-q\int_0^T\vv{OM}.\left(\vv{u}_z\times\vv{E}(M,t)\right)\,dt
        \end{align*}
      #+END_SRC
      or $\vv{E}(M,t)=\vv{E}(O,t)$ car l'onde EM est plane et le calcul se fait
      en $z=0$

      Calcul de \ding{193}
      #+BEGIN_SRC latex
        \begin{align*}
          \text{\ding{193}}&=q\int_0^T\vv{OM}\times\underbrace{\left(\vv{v}\times\vv{B}\right)}_{\vv{v}\perp\vv{B}=0}.\vv{u}_zdt
        \end{align*}
      #+END_SRC
      ou
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{a}\times\left(\vv{b}\times\vv{c}\right)=\left(\vv{a}.\vv{c}\right).\vv{b}-\left(\vv{a}.\vv{b}\right).\vv{c}
        \end{align*}
        \begin{align*}
          \text{\ding{193}}&=q\left[\int_0^T\left(\vv{OM}.\vv{B}\right).\underbrace{\vv{v}.\vv{u}_z}_{\vv{v}\perp\vv{u}_z=0}dt-\int_0^T\left(\vv{OM}.\vv{v}\right).\underbrace{\vv{B}.\vv{u}_z}_{\vv{B}\perp\vv{u}_z=0}dt\right]
        \end{align*}
      #+END_SRC

      Calcul de \ding{194} : $\vv{F}_\text{ext.}\perp\vv{u}_z$ sinon la
      particule ne serait plus maintenue dans le plan $z=0$ d'où
      $\vv{OM}\times\vv{F}_\text{ext.}=0$.

      Seul le champ électrique $\vv{E}$ de l'onde EM contribue au moment
      cinétique cédé à la particule $q$
      #+BEGIN_SRC latex
        \begin{align*}
          \sigma_z=-q\int_0^T\vv{OM}.\left(\vv{u}_z\times\vv{E}(O,t)\right)dt
        \end{align*}
      #+END_SRC
   4) Polarisation circulaire gauche
      #+BEGIN_SRC latex
        \begin{align*}
          \vv{E}(O,t)=
          \begin{pmatrix}
            E_0\cos\omega t\\E_0\sin\omega t\\0
          \end{pmatrix}
        \end{align*}
        \begin{align*}
          \frac{d\vv{E}(O,t)}{dt}=
          \begin{pmatrix}
            -E_0\sin\omega t\\E_0\cos\omega t\\0
          \end{pmatrix}
        \end{align*}
        \begin{align*}
          \vv{u}_z\times\vv{E}(O,t)=
          \begin{pmatrix}
            0\\0\\1
          \end{pmatrix}
          \times
          \begin{pmatrix}
            E_0\cos\omega t\\E_0\sin\omega t\\0
          \end{pmatrix}
          =
          \begin{pmatrix}
            -E_0\sin\omega t\\E_0\cos\omega t\\0
          \end{pmatrix}
          =\frac{1}{\omega}\,\frac{d\vv{E}(O,t)}{dt}
        \end{align*}
      #+END_SRC
      d'où
      #+BEGIN_SRC latex
        \begin{align*}
          \sigma_z=-\frac{q}{\omega}\int_0^T\vv{OM}.\frac{d\vv{E}(O,t)}{dt}dt
        \end{align*}
      #+END_SRC
      En intégrant par partie /i.e./ $(uv)^\prime=u^\prime v+v^\prime
      u\rightarrow\int u^\prime v=[uv]-\int v^\prime u$
      #+BEGIN_SRC latex
        \begin{align*}
          \sigma_z&=-\frac{q}{\omega}\left[\underbrace{\left[\vv{OM}.\vv{E}\right]_0^T}_{\vv{E}(O,0)=\vv{E}(O,T)}-\int_0^T\frac{d\vv{OM}}{dt}.\vv{E}(O,t)dt\right]\\
          &=\frac{q}{\omega}\int_0^T\vv{v}.\vv{E}(O,t)\,dt=\frac{W}{\omega}
        \end{align*}
      #+END_SRC

      $\omega=\tfrac{2\pi}{T}$ d'où $W=2\pi\frac{\sigma_z}{T}=\hbar\omega$ soit
      $\sigma_z=+\hbar$. Sur une période $T$, le champ EM cède à la particule
      $q$, un moment cinétique égal à $+\hbar$
   5) Le moment cinétique de photons polarisé circulairement droite est alors
      $-\hbar$, et $\sigma_z=0$ pour une polarisation rectiligne (rectligne
      \equiv circulaire droite + circulaire gauche)
* Footnotes

[fn:1] le vecteur accélération $\vv{a}$ s'écrit en toute rigueur
$(\ddot{r}-r\dot{\theta}^2)\vv{u}_r+(2\dot{r}\dot{\theta}+r\ddot{\theta})\vv{u}_\theta$. À
défaut de vitesse angulaire $\dot{\theta}$ initiale, on supposera donc que $\dot{\theta}=0$.
